<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>images\LogoTemp.ico</ApplicationIcon>
    <SignAssembly>false</SignAssembly>
    <AssemblyOriginatorKeyFile>LauncherKey.pfx</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="fonts\CONFN___.TTF" />
    <None Remove="fonts\primer print bold.ttf" />
    <None Remove="fonts\primer print.ttf" />
    <None Remove="images\BannerWhiteTransparent.png" />
    <None Remove="images\CarpWhite.png" />
    <None Remove="images\Download.png" />
    <None Remove="images\LogoTemp.ico" />
    <None Remove="images\LogoTempTransparent.png" />
    <None Remove="images\Screenshot_4.jpg" />
    <None Remove="images\SideAndHeekBackground.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="ControlTemplate.xaml" />
    <Page Remove="ItemTemplate.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ControlTemplate.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Resource>
    <Resource Include="images\BannerWhiteTransparent.png" />
    <Resource Include="images\CarpWhite.png" />
    <Resource Include="ItemTemplate.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Resource>
    <Resource Include="fonts\CONFN___.TTF" />
    <Resource Include="fonts\primer print bold.ttf" />
    <Resource Include="fonts\primer print.ttf" />
    <Resource Include="images\Download.png" />
    <Resource Include="images\LogoTemp.ico" />
    <Resource Include="images\LogoTempTransparent.png" />
    <Resource Include="images\Screenshot_4.jpg" />
    <Resource Include="images\SideAndHeekBackground.png" />
  </ItemGroup>

</Project>
